services:
  web:
    container_name: tch099-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80" # http://localhost:8001
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tch099-network

  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: tch099-db
    restart: always
    ports:
      - "3306:3306" # mysql://root:rootpassword@localhost:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tch099-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tch099-phpmyadmin
    restart: always
    ports:
      - "8060:80" # http://localhost:8060
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tch099-network

volumes:
  dbdata:

networks:
  tch099-network:
    driver: bridge
